"""Utility to remove autogenerated caches and empty static folder.
Run from project root (python scripts/remove_unneeded.py).
This script deletes all `__pycache__` directories and their contents,
and removes `app/static` if it's empty.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def remove_pycache(root: Path):
    removed = 0
    for p in root.rglob('__pycache__'):
        if p.is_dir():
            for f in p.iterdir():
                try:
                    f.unlink()
                    removed += 1
                except Exception:
                    pass
            try:
                p.rmdir()
            except Exception:
                pass
    return removed

def remove_empty_static(root: Path):
    static = root / 'app' / 'static'
    if static.exists() and static.is_dir():
        try:
            # remove if empty
            if not any(static.iterdir()):
                static.rmdir()
                return True
        except Exception:
            pass
    return False

if __name__ == '__main__':
    print('Removing __pycache__...')
    n = remove_pycache(ROOT)
    print(f'Removed {n} files from __pycache__ directories (if any).')
    removed_static = remove_empty_static(ROOT)
    if removed_static:
        print('Removed empty app/static/ folder.')
    else:
        print('No empty app/static/ folder removed.')
